services:
  - type: web
    name: bewdley-bootcamp
    env: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
